title: Exploring Digital Humanities in Classrooms
description: 'Testing out static site concepts'
theme: jekyll-theme-cayman

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: post
